#!/usr/bin/env bash
set -euo pipefail

# Generated by scripts/dimos_mcp_bridge_plan.py.
# Start an MCP-enabled DimOS blueprint first, for example:
#   dimos --simulation mujoco --viewer none --rerun-open none run unitree-go2-agentic --daemon
# Then inspect tools:
#   dimos mcp list-tools

# Dry-run command proposal:
echo ''"'"'/Users/espejelomar/StarkNet/zk-ai/_pr_work/dimos-worldforge-go2-trace-judge/.venv/bin/dimos'"'"' '"'"'mcp'"'"' '"'"'call'"'"' '"'"'relative_move'"'"' '"'"'--json-args'"'"' '"'"'{"degrees": 30.0, "forward": -0.5, "left": 0.3}'"'"''

# Live execution remains gated in the Python script:
#   WORLDFORGE_DIMOS_ENABLE_EXECUTE=1 python3 scripts/dimos_mcp_bridge_plan.py --execute --confirm LIVE_DIMOS_MCP_EXECUTE
