#!/usr/bin/env python3
"""Safe DimOS simulation capability probe.

This script intentionally does not start MuJoCo, connect to a robot, or invoke
DimOS MCP tools. It inspects local docs/code and optional CLI help so the next
simulation step can be run deliberately.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_DIMOS_REPO = Path(
    os.environ.get(
        "DIMOS_REPO",
        "/Users/espejelomar/StarkNet/zk-ai/_pr_work/dimos-worldforge-go2-trace-judge",
    )
)
DEFAULT_OUTPUT_DIR = ROOT / "artifacts" / "dimos_simulation_probe"


def read_text(path: Path) -> str:
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8", errors="replace")


def run_cmd(args: list[str], timeout_s: float) -> dict[str, Any]:
    try:
        proc = subprocess.run(
            args,
            check=False,
            capture_output=True,
            text=True,
            timeout=timeout_s,
        )
    except FileNotFoundError:
        return {"available": False, "error": "not found", "args": args}
    except subprocess.TimeoutExpired as exc:
        return {
            "available": True,
            "timeout": True,
            "args": args,
            "stdout": exc.stdout or "",
            "stderr": exc.stderr or "",
        }

    return {
        "available": True,
        "returncode": proc.returncode,
        "args": args,
        "stdout_preview": proc.stdout[:4000],
        "stderr_preview": proc.stderr[:4000],
    }


def extract_blueprints(dimos_repo: Path) -> list[str]:
    source = read_text(dimos_repo / "dimos" / "robot" / "all_blueprints.py")
    blueprints = sorted(set(re.findall(r'"(unitree-go2[^"]*)"', source)))
    return blueprints


def extract_doc_commands(dimos_repo: Path) -> list[str]:
    doc_paths = [
        dimos_repo / "docs" / "quickstart.mdx",
        dimos_repo / "docs" / "platforms" / "quadruped" / "go2" / "index.md",
        dimos_repo / "docs" / "usage" / "visualization.md",
    ]
    commands: list[str] = []
    for path in doc_paths:
        text = read_text(path)
        for line in text.splitlines():
            stripped = line.strip()
            if stripped.startswith("dimos ") or stripped.startswith("uv pip install"):
                if "unitree-go2" in stripped or "dimos[base,unitree,sim]" in stripped:
                    commands.append(stripped)
    return sorted(set(commands))


def source_status(dimos_repo: Path) -> dict[str, Any]:
    source_paths = {
        "go2_guide": dimos_repo / "docs" / "platforms" / "quadruped" / "go2" / "index.md",
        "quickstart": dimos_repo / "docs" / "quickstart.mdx",
        "visualization": dimos_repo / "docs" / "usage" / "visualization.md",
        "nav_stack": dimos_repo / "docs" / "capabilities" / "navigation" / "nav_stack.md",
        "go2_connection": dimos_repo / "dimos" / "robot" / "unitree" / "go2" / "connection.py",
        "mujoco_process": dimos_repo / "dimos" / "simulation" / "mujoco" / "mujoco_process.py",
    }
    return {name: {"path": str(path), "exists": path.exists()} for name, path in source_paths.items()}


def build_next_commands() -> list[dict[str, str]]:
    return [
        {
            "name": "install_sim_extra",
            "purpose": "Install DimOS simulation dependencies when ready.",
            "command": "uv pip install 'dimos[base,unitree,sim]'",
        },
        {
            "name": "replay_no_hardware",
            "purpose": "Replay Go2 navigation without robot hardware.",
            "command": "dimos --replay --viewer none run unitree-go2",
        },
        {
            "name": "mujoco_smoke",
            "purpose": "Run Go2 navigation stack in MuJoCo without opening a viewer.",
            "command": "dimos --simulation --viewer none run unitree-go2",
        },
        {
            "name": "agentic_mujoco_daemon",
            "purpose": "Start agentic Go2 simulation so MCP tools can be inspected.",
            "command": "dimos --simulation --viewer none run unitree-go2-agentic --daemon",
        },
        {
            "name": "mcp_tools",
            "purpose": "Confirm tool surface before any execution wrapper is added.",
            "command": "dimos mcp list-tools",
        },
        {
            "name": "local_replay_mpc_demo",
            "purpose": "Regenerate the no-robot WorldForge replay-MPC trace.",
            "command": "make replay-mpc-demo",
        },
    ]


def write_next_commands(path: Path, commands: list[dict[str, str]]) -> None:
    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        "# Generated by scripts/dimos_simulation_probe.py.",
        "# Run commands one by one; do not execute the whole file blindly.",
        "",
    ]
    for item in commands:
        lines.extend(
            [
                f"# {item['name']}: {item['purpose']}",
                item["command"],
                "",
            ]
        )
    path.write_text("\n".join(lines), encoding="utf-8")
    path.chmod(0o755)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dimos-repo", type=Path, default=DEFAULT_DIMOS_REPO)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument(
        "--skip-cli-help",
        action="store_true",
        help="Do not run `dimos --help`; useful if the CLI startup is slow.",
    )
    args = parser.parse_args()

    dimos_repo = args.dimos_repo.expanduser().resolve()
    output_dir = args.output_dir.expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    dimos_binary = shutil.which("dimos")
    cli_help = None
    if dimos_binary and not args.skip_cli_help:
        cli_help = run_cmd([dimos_binary, "--help"], timeout_s=8.0)

    commands = build_next_commands()
    report = {
        "schema_version": 1,
        "generated_by": "scripts/dimos_simulation_probe.py",
        "project_root": str(ROOT),
        "dimos_repo": str(dimos_repo),
        "dimos_repo_exists": dimos_repo.exists(),
        "dimos_binary": dimos_binary,
        "dimos_cli_help": cli_help,
        "go2_blueprints": extract_blueprints(dimos_repo) if dimos_repo.exists() else [],
        "doc_commands": extract_doc_commands(dimos_repo) if dimos_repo.exists() else [],
        "source_status": source_status(dimos_repo) if dimos_repo.exists() else {},
        "recommended_next_commands": commands,
        "safety_boundary": [
            "probe only; does not start simulation",
            "probe only; does not connect to robot",
            "probe only; does not call MCP tools",
        ],
    }

    (output_dir / "probe.json").write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    write_next_commands(output_dir / "next_commands.sh", commands)

    print(f"Wrote {output_dir / 'probe.json'}")
    print(f"Wrote {output_dir / 'next_commands.sh'}")
    print(f"DimOS repo exists: {report['dimos_repo_exists']}")
    print(f"DimOS CLI on PATH: {bool(dimos_binary)}")
    print(f"Go2 blueprints found: {len(report['go2_blueprints'])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
