#!/usr/bin/env bash
set -euo pipefail

# Generated by scripts/dimos_simulation_probe.py.
# Run commands one by one; do not execute the whole file blindly.

# install_sim_extra: Install DimOS simulation dependencies when ready.
uv pip install 'dimos[base,unitree,sim]'

# replay_no_hardware: Replay Go2 navigation without robot hardware.
dimos --replay --viewer none run unitree-go2

# mujoco_smoke: Run Go2 navigation stack in MuJoCo without opening a viewer.
dimos --simulation --viewer none run unitree-go2

# agentic_mujoco_daemon: Start agentic Go2 simulation so MCP tools can be inspected.
dimos --simulation --viewer none run unitree-go2-agentic --daemon

# mcp_tools: Confirm tool surface before any execution wrapper is added.
dimos mcp list-tools

# local_replay_mpc_demo: Regenerate the no-robot WorldForge replay-MPC trace.
make replay-mpc-demo
